return {
  lsp = {
    additionally_set_up = {
      rust = true,
      scala = true,
    },
    ensure_installed = {
      lsp = {
        "bashls",
        "clangd",
        "cssls",
        "jdtls",
        "jsonls",
        "lua_ls",
        "texlab",
        "yamlls",
        "rust_analyzer",
      },
      dap = {
        "bash-debug-adapter",
        "cpptools",
        "java-debug-adapter",
        "java-test",
      },
      null_ls = {
        "protolint",
        "beautysh",
        "black",
        "blue",
        "clang-format",
        "cmakelang",
        "codespell",
        "cpplint",
        "cspell",
        "golangci-lint",
        "isort",
        "ltex-ls",
        "prettierd",
        "selene",
        "shellcheck",
        "shfmt",
        "stylua",
        "textlint",
        "vale",
        "write-good",
        "yamlfmt",
        "yamllint",
        "google_java_format",
        "sql_formatter",
        "sqlfluff",
        "latexindent",
      },
    },
  },
}
