return {}
-- return {
--   "yetone/avante.nvim",
--   event = "VeryLazy",
--   lazy = true,
--   version = false, -- set this if you want to always pull the latest change
--   opts = {
--     ---@alias Provider "claude" | "openai" | "azure" | "gemini" | "cohere" | "copilot" | "ollama" [string]
--     provider = "ollama",
--     auto_suggestions_provider = "ollama",
--     use_absolute_path = true,
--     vendors = {
--       ---@type AvanteProvider
--       ollama = {
--         ["api_key_name"] = "",
--         endpoint = "http://localhost:11434/v1",
--         model = "magicoder",
--         parse_curl_args = function(opts, code_opts)
--           return {
--             url = opts.endpoint .. "/chat/completions",
--             headers = {
--               ["Accept"] = "application/json",
--               ["Content-Type"] = "application/json",
--               ["x-api-key"] = "ollama",
--             },
--             body = {
--               model = opts.model,
--               messages = require("avante.providers").openai.parse_messages(
--                 code_opts
--               ),
--               --   require("avante.providers").copilot.parse_message(
--               --   code_opts
--               -- ), -- you can make your own message, but this is very advanced
--               max_tokens = 2048,
--               stream = true,
--             },
--           }
--         end,
--         parse_response_data = function(data_stream, event_state, opts)
--           require("avante.providers").openai.parse_response(
--             data_stream,
--             event_state,
--             opts
--           )
--         end,
--       },
--     },
--     behaviour = {
--       auto_suggestions = true, -- Experimental stage
--       auto_set_highlight_group = true,
--       auto_set_keymaps = true,
--       auto_apply_diff_after_generation = false,
--       support_paste_from_clipboard = true,
--     },
--     mappings = {
--       --- @class AvanteConflictMappings
--       diff = {
--         ours = "co",
--         theirs = "ct",
--         all_theirs = "ca",
--         both = "cb",
--         cursor = "cc",
--         next = "]x",
--         prev = "[x",
--       },
--       suggestion = {
--         accept = "<M-l>",
--         next = "<M-]>",
--         prev = "<M-[>",
--         dismiss = "<C-]>",
--       },
--       jump = {
--         next = "]]",
--         prev = "[[",
--       },
--       submit = {
--         normal = "<CR>",
--         insert = "<C-s>",
--       },
--     },
--     hints = { enabled = true },
--     windows = {
--       ---@type "right" | "left" | "top" | "bottom"
--       position = "right", -- the position of the sidebar
--       wrap = true, -- similar to vim.o.wrap
--       width = 30, -- default % based on available width
--       sidebar_header = {
--         align = "center", -- left, center, right for title
--         rounded = true,
--       },
--     },
--     highlights = {
--       ---@type AvanteConflictHighlights
--       diff = {
--         current = "DiffText",
--         incoming = "DiffAdd",
--       },
--     },
--     --- @class AvanteConflictUserConfig
--     diff = {
--       autojump = true,
--       ---@type string | fun(): any
--       list_opener = "copen",
--     },
--   },
--   -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
--   build = "make BUILD_FROM_SOURCE=true",
--   -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
--   dependencies = {
--     "nvim-treesitter/nvim-treesitter",
--     "stevearc/dressing.nvim",
--     "nvim-lua/plenary.nvim",
--     "MunifTanjim/nui.nvim",
--     --- The below dependencies are optional,
--     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
--     {
--       -- support for image pasting
--       "HakonHarnes/img-clip.nvim",
--       event = "VeryLazy",
--       opts = {
--         -- recommended settings
--         default = {
--           embed_image_as_base64 = false,
--           prompt_for_file_name = false,
--           drag_and_drop = {
--             insert_mode = true,
--           },
--           -- required for Windows users
--           use_absolute_path = true,
--         },
--       },
--     },
--     {
--       -- Make sure to set this up properly if you have lazy=true
--       "MeanderingProgrammer/render-markdown.nvim",
--       opts = {
--         file_types = { "markdown", "Avante" },
--       },
--       ft = { "markdown", "Avante" },
--     },
--   },
--   keys = {
--     {
--       "<leader>aa",
--       function()
--         require("avante.api").ask()
--       end,
--       desc = "avante: ask",
--       mode = { "n", "v" },
--     },
--     {
--       "<leader>ar",
--       function()
--         require("avante.api").refresh()
--       end,
--       desc = "avante: refresh",
--     },
--     {
--       "<leader>ae",
--       function()
--         require("avante.api").edit()
--       end,
--       desc = "avante: edit",
--       mode = "v",
--     },
--   },
-- }
