return {
  -- url = "ssh://git@gitlab.tcsbank.ru:7999/nestor/assistant.git",
  -- name = "nestor",
  -- dependencies = { "nvim-lua/plenary.nvim" },
  -- config = function(plugin)
  --   vim.opt.rtp:append(plugin.dir .. "/neovim_plugin")
  --   -- This is needed for nestor docs to be picked up after editing rtp
  --   vim.cmd("helptags ALL")
  --   require("nestor").setup({
  --     auth = {
  --       dp_versions_url = "https://devplatform.tcsbank.ru/static/cli/dp/config.json",
  --       nestor_token_url = "https://code-completion-nestor.tcsbank.ru/api/v2/token",
  --     },
  --     suggestions = {
  --       max_prompt_lines = 150,
  --       debounce_ms = 150,
  --       client = {
  --         inline_completion_url = "https://code-completion-nestor.tcsbank.ru/api/v2/inline-completion",
  --         block_completion_url = "https://code-completion-nestor.tcsbank.ru/api/v2/block-completion",
  --       },
  --       keymaps = {
  --         accept = "<Tab>",
  --         dismiss = "<C-L>",
  --       },
  --       disabled_filetypes = { "TelescopePrompt" },
  --     },
  --     debug_enabled = false,
  --   })
  -- end,
}
